### ISSUE TITLE
'ENOTFOUND' when activating mongodb pod

### ISSUE THREAD

**Issue by svdev** [bipio-server/bip-pod-mongodb#1] opened 2015-03-21 18:46 UTC
Hello,

I tried to activate on a self-hosted bipio-server instance the mongodb pod but I got the following server.log msg:

info: WORKER:PID:30590:1426962895613:[a841e934-9348-477a-a76a-2d2277726ee4] ISSUER_TOKEN mongodb SET
Trace: { [Error: queryA ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'queryA' }
    at Object.app.logmessage [as _logger](/home/ubuntu/nodejs/node_modules/bipio/src/bootstrap.js:113:13)
    at /home/ubuntu/nodejs/node_modules/bipio/node_modules/bip-pod/index.js:781:24
    at /home/ubuntu/nodejs/node_modules/bipio/node_modules/bip-pod/index.js:509:7
    at /home/ubuntu/nodejs/node_modules/bipio/node_modules/bip-pod/index.js:76:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete](dns.js:149:9)
error: WORKER:PID:30590:1426962895615:Error: queryA ENOTFOUND

The format of the connection URI that I'm entering is in the form of:

mongodb://storer:storer@localhost/stored

If I try to connect locally through the shell it works. Anyone with similar issues?

Thanks

**Comment by svdev** [comment] 2015-03-21 18:50
I forgot to mention: my default.json file looks like this for the mongodb pod configuration:

```
    "mongodb": {
        "whitelist": []
    }
```

**Comment by mjpearson** [comment] 2015-03-22 01:36
Hi, does `localhost` resolve to 127.0.0.1 correctly on that server?

**Comment by svdev** [comment] 2015-03-22 18:20
This is my test scenario:

I have ec2 instance with bipio server installed and mongodb pod installed as well. I created locally tunnels to the ec2 instance for following ports:

local port 27017 -> remote port 27017 (mongodb)
local port 443 -> remote port 5000
local port 5000 -> remote port 5000

Both on my local server and ec2 server localhost resolves to 127.0.0.1 correctly. I was able to enable other pods with this same configuration through bip.io UI, but not mongodb. 

My node version is: v0.10.25

I saw something related, could this be the issue ?
https://gist.github.com/commadelimited/5a564b1fa1bec2b44540

Thanks

**Comment by svdev** [comment] 2015-03-22 20:19
Hi Michael,

I found the issue at line 75 of https://github.com/bipio-server/bip-pod/blob/master/index.js:

dns.resolve(resolvingHost, function(err, aRecords) {
        next(err, aRecords, resolvingHost );
});

I debugged it and on my EC2 instance resolving "localhost" to 127.0.0.1 failed, so I got a value of aRecords undefined. Even having in my /etc/hosts 127.0.0.1 localhost does not help. 

I forced for the sake of testing it to:

dns.resolve(resolvingHost, function(err, aRecords) {
err = false;
aRecords = ['127.0.0.1'];
     next(err, aRecords, resolvingHost );
});

And the pod installed correctly.

**Comment by mjpearson** [comment] 2015-03-23 17:45
Hi, thanks for the detail!

 I was able to reproduce the error and tracked down an issue in a dependent module.  The `resolvingHost` variable was being set to 'mongodb' because the URL was being parsed incorrectly.

 npm update on the server should grab a new bip-pod package (0.3.14) and tldtools (0.0.23) dependency which should solve it

**Closed as completed** 2015-03-24 14:04 UTC
